---
name: Release
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  print-debug-info:
    name: Print debug info for Release workflow
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2

  create-release:
    name: Create release
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'release/') }}
    uses: NikitaSkrynnik/.github/.github/workflows/release.yaml@release-act
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
